title: ENGL 3630 / AMST 3632
description: US Literature and the End of the American Century. Cornell University, Spring 2024. Professor Lindsay Thomas
theme: just-the-docs

url: https://lindsaythomas.net/engl3630s24

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
